services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream_arabic/pipeline_conf.json'
    environment:
      WAIT_HOSTS: "dff-arabic-greeting-skill:8138, rule-based-response-selector:8005"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1200}
      HIGH_PRIORITY_INTENTS: 1
      RESTRICTION_FOR_SENSITIVE_CASE: 1
      ALWAYS_TURN_ON_ALL_SKILLS: 0
      LANGUAGE: AR


  dff-arabic-greeting-skill:
    env_file: [ .env_ru ]
    build:
      args:
        SERVICE_PORT: 8138
        SERVICE_NAME: dff_arabic_greeting_skill
      context: .
      dockerfile: ./skills/dff_arabic_greeting_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8138 --reload
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

  rule-based-response-selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8005
    volumes: []
    ports:
      - 8005:8005

version: '3.7'
